# Generated by Django 5.0.6 on 2024-06-08 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fullname', models.CharField(max_length=255)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('shipping_postcode', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
