# Generated by Django 5.0.6 on 2024-06-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
