# Generated by Django 5.0.6 on 2024-06-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
